In [1]:
import IPython
import json
# Numpy is a library for working with Arrays
import numpy as np
# SciPy implements many different numerical algorithms
import scipy as sp
# Pandas is good with data tables
import pandas as pd
# Module for plotting
import matplotlib
#BeautifulSoup parses HTML documents (once you get them via requests)
import bs4
# Nltk helps with some natural language tasks, like stemming
import nltk
# Bson is a binary format of json to be stored in databases
import bson
# Mongo is one of common nosql databases 
# it stores/searches json documents natively
import pymongo
print ("IPython version:      %6.6s", IPython.__version__)

IPython version:      %6.6s 8.3.0


In [3]:
#Here is what numpy can do\n",
print ("Make a 2 row x 3 column array of random numbers")
x = np.random.random((2, 3))
print (x)

#array operation (as in R)
print ("Add 5 to every element")
x = x + 5
print (x)

# get a slice (first row) (as in R)
print ("Get the first row")
print (x[0, :])

Make a 2 row x 3 column array of random numbers
[[0.93782518 0.7297478  0.55157621]
 [0.31996306 0.10694138 0.35130828]]
Add 5 to every element
[[5.93782518 5.7297478  5.55157621]
 [5.31996306 5.10694138 5.35130828]]
Get the first row
[5.93782518 5.7297478  5.55157621]


In [4]:
# IPython is quite modern: just press <TAB> at the end of the unfinished statement to see the documentation
#       on possible completions.
#       In the code cell below, type x.<TAB>, to find built-in operations for x
x.any

<function ndarray.any>

In [ ]:
%matplotlib inline 
import matplotlib.pyplot as plt
heads = np.random.binomial(500, .5, size=500)
histogram = plt.hist(heads, bins=10)

# Task 1
## write a program to produce Fibonacci numbers up to 1000000

In [ ]:
up_to = 1000000
at1 = 0
at2 = 1
while at1 < up_to:
    print(at1)
    at2 = at1 + at2
    at1 = at2 - at1

# Task 2
## write a program to simulate 1000 tosses of a fair coin (use np.random.binomial)
## Calculate the mean and standard deviation of that sample

In [ ]:

s = np.random.binomial(1, .5, 1000)
total = 0;
for a in s:
    total += a;
print("mean = ", total/1000)
print("standard deviation = ", np.std(s))

# Task 3
## Produce a scatterplot of y = 0.5*x+e where x has gaussian (0, 5) and e has gaussian (0, 1) distributions 
### use numpy.random.normal to generate gaussian distribution

In [ ]:
x = np.random.normal(0, 5, 100)
e = np.random.normal(0, 1, 100)
y = .5*x+e
plt.scatter(x,y)